version: "3"

services:
  db:
    image: postgres:latest
    container_name: dyna-db
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - app-db-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: on-failure

  app:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: production
    container_name: dyna-app
    ports:
      - 3333:3333
    networks:
      - app-db-network
    depends_on:
      - db
    restart: on-failure

volumes:
  app-db-data:
    driver: local

networks:
  app-db-network:
    driver: bridge
